### ISSUE TITLE
Admin Edit: Implement Elements

### ISSUE THREAD

**Issue by Salehkhatib** [coding-bootcamps-eu/final-project-class-september#10]
#Todos

-  [ ] Create Formular  to Create an entry
-  [ ] Formular contains Created Elements

# Bonus
- [ ] Elements used are Components
