### ISSUE TITLE
Admin Listing: Router path  & basic render logic admin

### ISSUE THREAD

**Issue by ColaAlin** [coding-bootcamps-eu/final-project-class-september#12]
#Todos

- [x] Add Router
- [x] implement 2 Main Pages Public and Admin
- [x] implement dynamic Edit Page for Admin -> /admin/edit/:id",
- [x] route/path /admin
- [x] route/path /public
- [x] Public Page is also in "/" (home)
- [x] Basic render logic admin: Implement table with basic layout
- [x] v-for loop for rendering entries
