### ISSUE TITLE
General: Implement Production Api

### ISSUE THREAD

**Issue by Matthias-Mosthof** [coding-bootcamps-eu/final-project-class-september#21]
# Todo

- [x] implement Production API 
- [x] Load data Initial Using created Hook
- [x] Render Data in browser (v-for)
- [x] also created custom events see Issue #26
