### ISSUE TITLE
Public: Create Style/Layout for Public Main Page

### ISSUE THREAD

**Issue by Matthias-Mosthof** [coding-bootcamps-eu/final-project-class-september#23]
## Todos

- [ ] implement existing components 
- [ ] position and if necessary style imported elements
- [ ]  background/color/img
- [ ] create post for user and admin 
- [ ] cursor: pointer; for every  button
