### ISSUE TITLE
Implement Logic across the app

### ISSUE THREAD

**Issue by Matthias-Mosthof** [coding-bootcamps-eu/final-project-class-september#36]
## Todos

- [x] changed localhost routing to vue routing
- [x] function to delete entries
- [x] function to release entries
- [x] Title is now href with the URL of provided URL -> Click on title leads to the Site
- [x] Suggestions can now be created -> only seen in AdminPage -> Admin has to release in order to see it in PublicPage
- [x] implemented Searchfunction in PublicPage
- [x] conditional rendring: CbeAnnouncement posts are now highlighted in Public Page.
