### ISSUE TITLE
all - ref styling

### ISSUE THREAD

**Issue by CarolinJenner** [coding-bootcamps-eu/final-project-class-september#43]
#Todo
- [x] footer @admin
- [x] font weight @admin
- [x] links right @admin
- [x] gap btn @admin
- [x] cbe an. styling @public
