### ISSUE TITLE
Implement Visual Feedback @events

### ISSUE THREAD

**Issue by Matthias-Mosthof** [coding-bootcamps-eu/final-project-class-september#45]
## Todos

- [x] Message for user when succesfully suggested
- [x] Visual Feedback when admin releases a suggestion
- [x] Message when admin created an entry
- [x] Entries which are not active should look different than active entries

## Bonus
- [x] implement Counter of unreleased suggestions
