### ISSUE TITLE
go thru the code line in CSS and delete no used code

### ISSUE THREAD

**Issue by ColaAlin** [coding-bootcamps-eu/final-project-class-september#49]
#Todos

- [x] clear unused code
- [x] check the app
- [x] CBE announcement styling
- [x] arrow in place
- [x] create form center admin/user
