### ISSUE TITLE
Refactor Script code

### ISSUE THREAD

**Issue by Matthias-Mosthof** [coding-bootcamps-eu/final-project-class-september#58]
## Todos

- [x] Deleting all console.logs
- [x] Perhabs refactor code so it can be less lines
- [x] Delete un-used code if there is any
