### ISSUE TITLE
Admin Listing: Implement Logic

### ISSUE THREAD

**Issue by Salehkhatib** [coding-bootcamps-eu/final-project-class-september#8]
#Todos
- [x] Get data from api
- [ ] implement search with api
- [ ] implement filters

#Bonus
- [x] One component on Inputfield 
- [x] One component with Button
- [ ] One component for Pop Up
